version: "3.7"

services:
  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./ops/nginx/conf.d.dev:/etc/nginx/conf.d:ro
      
  api:
    build:
      dockerfile: src/FilterLists.Api/debug.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${API_ASPNETCORE_ENVIRONMENT}